version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: booking-system-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./vendor:/var/www/vendor
      - ./node_modules:/var/www/node_modules
    ports:
      - "8000:8000"
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: booking_system
      DB_USERNAME: root
      DB_PASSWORD:
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    container_name: booking_system-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: booking_system
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: booking_system-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8081:80"
    depends_on:
      db:
        condition: service_healthy

volumes:
  dbdata:
